# Generated by Django 4.1.2 on 2022-12-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freskbackend', '0015_alter_contactform_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktualnosci',
            name='content_preview',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
